-- Reconstructs the legacy Poker Ledger schema for local resets and new
-- environments. Every statement is additive so existing hosted projects keep
-- their data when this baseline is reconciled into migration history.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  is_public boolean not null default false,
  theme_mode text not null default 'system'
    check (theme_mode in ('system', 'light', 'dark')),
  tutorial_completed boolean not null default false,
  deleted_at timestamptz,
  deletion_scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  notes text,
  active boolean not null default true,
  linked_user_id uuid references auth.users(id) on delete set null,
  was_linked_to_deleted_user boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  name text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  finalized boolean not null default false,
  settlement_mode text not null default 'pairwise'
    check (settlement_mode in ('pairwise', 'banker')),
  banker_session_player_id bigint
);

create table if not exists public.session_players (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  buy_in_cents_total bigint not null default 0
    check (buy_in_cents_total >= 0),
  cash_out_cents bigint check (cash_out_cents is null or cash_out_cents >= 0),
  paid_upfront boolean not null default false,
  settlement_done boolean not null default false,
  unique (session_id, player_id)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'sessions_banker_session_player_id_fkey'
  ) then
    alter table public.sessions
      add constraint sessions_banker_session_player_id_fkey
      foreign key (banker_session_player_id)
      references public.session_players(id)
      on delete set null;
  end if;
end;
$$;

create table if not exists public.rebuys (
  id bigint generated by default as identity primary key,
  session_player_id bigint not null
    references public.session_players(id) on delete cascade,
  amount_cents bigint not null check (amount_cents > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (group_id, user_id)
);

create table if not exists public.session_groups (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  added_at timestamptz not null default now(),
  unique (session_id, group_id)
);

create table if not exists public.quick_add_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  amount_cents bigint not null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.follows (
  id integer generated by default as identity primary key,
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.deleted_user_group_members (
  id bigint generated by default as identity primary key,
  deleted_user_id uuid not null references auth.users(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  original_joined_at timestamptz not null,
  backed_up_at timestamptz not null default now()
);

create table if not exists public.deleted_user_follows (
  id bigint generated by default as identity primary key,
  deleted_user_id uuid not null references auth.users(id) on delete cascade,
  follower_id uuid references auth.users(id) on delete set null,
  following_id uuid references auth.users(id) on delete set null,
  original_status text not null,
  original_created_at timestamptz not null,
  backed_up_at timestamptz not null default now()
);

create table if not exists public.deleted_user_player_links (
  id bigint generated by default as identity primary key,
  deleted_user_id uuid not null references auth.users(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  player_owner_id uuid not null references auth.users(id) on delete cascade,
  original_player_name text not null,
  backed_up_at timestamptz not null default now()
);

create table if not exists public.deleted_user_session_groups (
  id bigint generated by default as identity primary key,
  deleted_user_id uuid not null references auth.users(id) on delete cascade,
  session_id bigint not null references public.sessions(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  original_added_at timestamptz not null,
  backed_up_at timestamptz not null default now()
);

create table if not exists public.deleted_user_group_ownership (
  id integer generated by default as identity primary key,
  deleted_user_id uuid not null,
  group_id bigint not null,
  group_name text not null,
  new_owner_id uuid,
  backed_up_at timestamptz default now()
);

create index if not exists players_user_id_idx
  on public.players(user_id);
create index if not exists players_linked_user_id_idx
  on public.players(linked_user_id);
create index if not exists sessions_user_id_started_at_idx
  on public.sessions(user_id, started_at desc);
create index if not exists session_players_session_id_idx
  on public.session_players(session_id);
create index if not exists rebuys_session_player_id_idx
  on public.rebuys(session_player_id);
create index if not exists group_members_user_id_idx
  on public.group_members(user_id);
create index if not exists session_groups_group_id_idx
  on public.session_groups(group_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
