-- Propagate finalized-ledger rules into transfer tracking and close remaining
-- group archival compatibility gaps.

create table if not exists public.settlement_transfer_status_history (
  id bigint generated by default as identity primary key,
  transfer_id bigint not null
    references public.settlement_transfers(id) on delete restrict,
  previous_status text not null,
  new_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  check (previous_status in ('pending', 'paid', 'received', 'disputed')),
  check (new_status in ('pending', 'paid', 'received', 'disputed'))
);
alter table public.settlement_transfer_status_history
  add column if not exists changed_by_snapshot text;
update public.settlement_transfer_status_history history
set changed_by_snapshot = profile.display_name
from public.profiles profile
where history.changed_by = profile.id
  and history.changed_by_snapshot is null;
create or replace function private.snapshot_transfer_status_actor()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.changed_by_snapshot is null and new.changed_by is not null then
    select display_name into new.changed_by_snapshot
    from public.profiles
    where id = new.changed_by;
  end if;
  return new;
end;
$$;
drop trigger if exists transfer_status_snapshot_actor
  on public.settlement_transfer_status_history;
create trigger transfer_status_snapshot_actor
  before insert on public.settlement_transfer_status_history
  for each row execute function private.snapshot_transfer_status_actor();
create index if not exists settlement_transfer_history_transfer_idx
  on public.settlement_transfer_status_history(transfer_id, changed_at);
alter table public.settlement_transfer_status_history enable row level security;
revoke all on public.settlement_transfer_status_history
  from anon, authenticated;
grant select on public.settlement_transfer_status_history to authenticated;
drop policy if exists settlement_transfer_history_select_visible
  on public.settlement_transfer_status_history;
create policy settlement_transfer_history_select_visible
  on public.settlement_transfer_status_history for select
  using (
    exists (
      select 1
      from public.settlement_transfers transfer
      join public.finalization_revisions revision
        on revision.id = transfer.revision_id
      where transfer.id = transfer_id
        and public.can_view_session(revision.session_id)
    )
  );
revoke update on public.settlement_transfers from anon, authenticated;

create or replace function public.update_settlement_transfer_status(
  p_transfer_id bigint,
  p_status text,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  transfer public.settlement_transfers;
  revision public.finalization_revisions;
  game public.sessions;
  payer_profile_id uuid;
  recipient_profile_id uuid;
  prior jsonb;
  result jsonb;
begin
  perform private.require_compatible_client();
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'update_settlement_transfer_status',
    jsonb_build_object('transfer_id', p_transfer_id, 'status', p_status)
  );
  if prior is not null then return prior; end if;
  if p_status not in ('paid', 'received', 'disputed') then
    raise exception 'Unsupported transfer status' using errcode = '22023';
  end if;
  select * into transfer
  from public.settlement_transfers
  where id = p_transfer_id
  for update;
  if not found then
    raise exception 'Settlement transfer not found' using errcode = 'P0002';
  end if;
  select * into revision
  from public.finalization_revisions
  where id = transfer.revision_id;
  select * into game
  from public.sessions
  where id = revision.session_id;
  if game.phase <> 'finalized'
     or game.latest_revision_id <> revision.id then
    raise exception 'Only transfers in the current finalized revision can change'
      using errcode = '22023';
  end if;
  if exists (
    select 1 from public.groups grouped
    where grouped.id = game.group_id
      and grouped.archived_at is not null
  ) then
    raise exception 'Archived group games are read-only'
      using errcode = '55000';
  end if;
  select profile_id into payer_profile_id
  from public.session_players
  where id = transfer.from_participant_id;
  select profile_id into recipient_profile_id
  from public.session_players
  where id = transfer.to_participant_id;
  if transfer.status = p_status then
    result := jsonb_build_object(
      'transfer_id', transfer.id,
      'status', transfer.status
    );
    perform private.complete_idempotent(actor, p_idempotency_key, result);
    return result;
  end if;
  if p_status = 'paid' and not (
    payer_profile_id = actor
    and transfer.status in ('pending', 'disputed')
  ) then
    raise exception 'Only the payer can mark this transfer paid'
      using errcode = '42501';
  elsif p_status = 'received' and not (
    recipient_profile_id = actor
    and transfer.status = 'paid'
  ) then
    raise exception 'The recipient can confirm only a paid transfer'
      using errcode = '42501';
  elsif p_status = 'disputed' and not (
    actor in (payer_profile_id, recipient_profile_id)
    and transfer.status <> 'received'
  ) then
    raise exception 'Only a transfer participant can dispute it'
      using errcode = '42501';
  end if;
  insert into public.settlement_transfer_status_history (
    transfer_id, previous_status, new_status, changed_by
  )
  values (transfer.id, transfer.status, p_status, actor);
  update public.settlement_transfers
  set status = p_status,
      status_updated_by = actor,
      status_updated_at = now()
  where id = transfer.id;
  result := jsonb_build_object(
    'transfer_id', transfer.id,
    'status', p_status
  );
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  perform private.log_v2_operation(
    'update_settlement_transfer_status', game.id, game.phase
  );
  return result;
end;
$$;

revoke all on function public.update_settlement_transfer_status(
  bigint, text, uuid
) from public, anon;
grant execute on function public.update_settlement_transfer_status(
  bigint, text, uuid
) to authenticated;

create or replace function public.archive_group(
  p_group_id bigint,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  prior jsonb;
  result jsonb;
begin
  perform private.require_compatible_client();
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'archive_group',
    jsonb_build_object('group_id', p_group_id)
  );
  if prior is not null then return prior; end if;
  if not exists (
    select 1 from public.groups
    where id = p_group_id and owner_id = actor
    for update
  ) then
    raise exception 'Only the group owner can archive this group'
      using errcode = '42501';
  end if;
  if exists (
    select 1
    from public.sessions game
    where (
      game.group_id = p_group_id
      or exists (
        select 1 from public.session_groups legacy_group
        where legacy_group.session_id = game.id
          and legacy_group.group_id = p_group_id
      )
    )
      and (
        (game.ledger_version = 2 and game.phase in ('draft', 'live', 'settling'))
        or (game.ledger_version = 1 and not game.finalized)
      )
  ) then
    raise exception 'Finalize or cancel open group games first'
      using errcode = '22023';
  end if;
  update public.groups
  set archived_at = coalesce(archived_at, now()),
      updated_at = now()
  where id = p_group_id;
  update public.group_invitations
  set status = 'cancelled',
      responded_at = now()
  where group_id = p_group_id
    and status = 'pending';
  result := jsonb_build_object('group_id', p_group_id, 'archived', true);
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  return result;
end;
$$;

revoke all on function public.archive_group(bigint, uuid) from public, anon;
grant execute on function public.archive_group(bigint, uuid) to authenticated;

create or replace function public.return_v2_session_to_live(
  p_session_id bigint,
  p_reason text,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  game public.sessions;
  prior jsonb;
  result jsonb;
begin
  perform private.require_compatible_client();
  if nullif(btrim(p_reason), '') is null then
    raise exception 'A reason is required to return to the live ledger'
      using errcode = '22023';
  end if;
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'return_v2_session_to_live',
    jsonb_build_object('session_id', p_session_id, 'reason', btrim(p_reason))
  );
  if prior is not null then return prior; end if;
  game := private.require_v2_host(p_session_id);
  if game.phase <> 'settling' or game.latest_revision_id is not null then
    raise exception 'Only an unfinalized settlement can return to live'
      using errcode = '22023';
  end if;
  update public.sessions
  set phase = 'live',
      updated_at = now()
  where id = p_session_id;
  result := jsonb_build_object(
    'session_id', p_session_id,
    'phase', 'live',
    'membership_closed', true,
    'reason', btrim(p_reason)
  );
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  perform private.log_v2_operation(
    'return_v2_session_to_live', p_session_id, 'live'
  );
  return result;
end;
$$;

revoke all on function public.return_v2_session_to_live(
  bigint, text, uuid
) from public, anon;
grant execute on function public.return_v2_session_to_live(
  bigint, text, uuid
) to authenticated;

create or replace function public.cancel_v2_session(
  p_session_id bigint,
  p_reason text,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  game public.sessions;
  prior jsonb;
  result jsonb;
begin
  perform private.require_compatible_client();
  if nullif(btrim(p_reason), '') is null then
    raise exception 'A cancellation reason is required'
      using errcode = '22023';
  end if;
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'cancel_v2_session',
    jsonb_build_object('session_id', p_session_id, 'reason', btrim(p_reason))
  );
  if prior is not null then return prior; end if;
  game := private.require_v2_host(p_session_id);
  if game.phase in ('finalized', 'cancelled') then
    raise exception 'This game cannot be cancelled'
      using errcode = '22023';
  end if;
  update public.game_join_codes
  set revoked_at = coalesce(revoked_at, now())
  where session_id = p_session_id;
  update public.game_invitations
  set status = 'cancelled',
      cancelled_at = now()
  where session_id = p_session_id
    and status in ('pending_invitee', 'pending_host');
  update public.sessions
  set phase = 'cancelled',
      membership_closed_at = coalesce(membership_closed_at, now()),
      ended_at = coalesce(ended_at, now()),
      updated_at = now()
  where id = p_session_id;
  result := jsonb_build_object(
    'session_id', p_session_id,
    'phase', 'cancelled',
    'reason', btrim(p_reason)
  );
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  perform private.log_v2_operation(
    'cancel_v2_session', p_session_id, 'cancelled'
  );
  return result;
end;
$$;

revoke all on function public.cancel_v2_session(bigint, text, uuid)
  from public, anon;
grant execute on function public.cancel_v2_session(bigint, text, uuid)
  to authenticated;

create or replace function private.guard_legacy_financial_rows()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  game public.sessions;
  target_session_id bigint;
begin
  if tg_table_name = 'session_players' then
    target_session_id := coalesce(new.session_id, old.session_id);
  else
    select participant.session_id into target_session_id
    from public.session_players participant
    where participant.id = coalesce(
      new.session_player_id,
      old.session_player_id
    );
  end if;
  select * into game
  from public.sessions
  where id = target_session_id;
  if current_user in ('authenticated', 'anon')
     and (game.ledger_version = 2 or game.finalized) then
    raise exception 'Use the transactional ledger API for this game'
      using errcode = '55000';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists session_players_guard_financial_rows
  on public.session_players;
create trigger session_players_guard_financial_rows
  before insert or update or delete on public.session_players
  for each row execute function private.guard_legacy_financial_rows();

create or replace function private.guard_direct_v2_session_write()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if current_user in ('authenticated', 'anon')
     and (
       new.ledger_version = 2
       or (tg_op = 'UPDATE' and old.ledger_version = 2)
     ) then
    raise exception 'Use the transactional game API for version 2 games'
      using errcode = '55000';
  end if;
  return new;
end;
$$;

drop trigger if exists sessions_guard_direct_v2_write on public.sessions;
create trigger sessions_guard_direct_v2_write
  before insert or update on public.sessions
  for each row execute function private.guard_direct_v2_session_write();

create or replace function private.guard_archived_group()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if current_user in ('authenticated', 'anon')
     and old.archived_at is not null then
    raise exception 'Archived groups are read-only'
      using errcode = '55000';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists groups_guard_archived on public.groups;
create trigger groups_guard_archived
  before update or delete on public.groups
  for each row execute function private.guard_archived_group();

create or replace function private.require_v2_host(p_session_id bigint)
returns public.sessions
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  game public.sessions;
begin
  select * into game
  from public.sessions
  where id = p_session_id
  for update;
  if not found or game.ledger_version <> 2 then
    raise exception 'Game not found' using errcode = 'P0002';
  end if;
  if game.current_host_id is distinct from actor then
    raise exception 'Only the current host can perform this action'
      using errcode = '42501';
  end if;
  if exists (
    select 1
    from public.groups grouped
    where grouped.id = game.group_id
      and grouped.archived_at is not null
  ) then
    raise exception 'Archived group games are read-only'
      using errcode = '55000';
  end if;
  return game;
end;
$$;

create or replace function public.add_legacy_rebuy(
  p_session_player_id bigint,
  p_amount_cents bigint,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  participant public.session_players;
  game public.sessions;
  prior jsonb;
  result jsonb;
begin
  if p_amount_cents <= 0 then
    raise exception 'Rebuy must be greater than zero'
      using errcode = '22023';
  end if;
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'add_legacy_rebuy',
    jsonb_build_object(
      'session_player_id', p_session_player_id,
      'amount_cents', p_amount_cents
    )
  );
  if prior is not null then return prior; end if;
  select * into participant
  from public.session_players
  where id = p_session_player_id
  for update;
  select * into game
  from public.sessions
  where id = participant.session_id
  for update;
  if not found
     or game.ledger_version <> 1
     or game.finalized
     or game.user_id <> actor then
    raise exception 'Legacy game is not editable'
      using errcode = '42501';
  end if;
  insert into public.rebuys (session_player_id, amount_cents)
  values (participant.id, p_amount_cents);
  update public.session_players
  set buy_in_cents_total = buy_in_cents_total + p_amount_cents
  where id = participant.id;
  result := jsonb_build_object(
    'session_player_id', participant.id,
    'buy_in_cents_total',
    participant.buy_in_cents_total + p_amount_cents
  );
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  return result;
end;
$$;

create or replace function public.set_legacy_cash_out(
  p_session_player_id bigint,
  p_cash_out_cents bigint,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  participant public.session_players;
  game public.sessions;
  prior jsonb;
  result jsonb;
begin
  if p_cash_out_cents is not null and p_cash_out_cents < 0 then
    raise exception 'Cash-out cannot be negative' using errcode = '22023';
  end if;
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'set_legacy_cash_out',
    jsonb_build_object(
      'session_player_id', p_session_player_id,
      'cash_out_cents', p_cash_out_cents
    )
  );
  if prior is not null then return prior; end if;
  select * into participant
  from public.session_players
  where id = p_session_player_id
  for update;
  select * into game
  from public.sessions
  where id = participant.session_id
  for update;
  if not found
     or game.ledger_version <> 1
     or game.finalized
     or game.user_id <> actor then
    raise exception 'Legacy game is not editable'
      using errcode = '42501';
  end if;
  update public.session_players
  set cash_out_cents = p_cash_out_cents
  where id = participant.id;
  result := jsonb_build_object(
    'session_player_id', participant.id,
    'cash_out_cents', p_cash_out_cents
  );
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  return result;
end;
$$;

revoke all on function public.add_legacy_rebuy(bigint, bigint, uuid)
  from public, anon;
revoke all on function public.set_legacy_cash_out(bigint, bigint, uuid)
  from public, anon;
grant execute on function public.add_legacy_rebuy(bigint, bigint, uuid)
  to authenticated;
grant execute on function public.set_legacy_cash_out(bigint, bigint, uuid)
  to authenticated;

create or replace function private.notify_game_invitation_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  game_name text;
  profile_name text;
  recipient uuid;
begin
  select coalesce(name, 'Poker game') into game_name
  from public.sessions where id = new.session_id;
  select coalesce(display_name, 'Poker Ledger player') into profile_name
  from public.profiles where id = new.profile_id;
  if tg_op = 'INSERT' then
    recipient := case
      when new.direction = 'host_invite' then new.profile_id
      else (
        select current_host_id from public.sessions where id = new.session_id
      )
    end;
    if recipient is not null then
      insert into public.user_notifications (
        user_id, notification_type, title, body, data
      )
      values (
        recipient,
        case
          when new.direction = 'host_invite' then 'game_invitation'
          else 'game_join_request'
        end,
        case
          when new.direction = 'host_invite' then 'Game invitation'
          else 'Game join request'
        end,
        case
          when new.direction = 'host_invite'
            then 'You were invited to ' || game_name || '.'
          else profile_name || ' requested to join ' || game_name || '.'
        end,
        jsonb_build_object(
          'session_id', new.session_id,
          'invitation_id', new.id
        )
      );
    end if;
  elsif old.status is distinct from new.status
     and new.status in ('accepted', 'declined') then
    recipient := case
      when new.direction = 'host_invite' then new.created_by
      else new.profile_id
    end;
    if recipient is not null and recipient <> auth.uid() then
      insert into public.user_notifications (
        user_id, notification_type, title, body, data
      )
      values (
        recipient,
        'game_invitation_response',
        'Game invitation updated',
        case
          when new.direction = 'host_invite'
            then profile_name || ' ' || new.status ||
              ' the invitation to ' || game_name || '.'
          else 'Your request to join ' || game_name || ' was ' ||
            new.status || '.'
        end,
        jsonb_build_object(
          'session_id', new.session_id,
          'invitation_id', new.id,
          'status', new.status
        )
      );
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists game_invitations_notify_change
  on public.game_invitations;
create trigger game_invitations_notify_change
  after insert or update of status on public.game_invitations
  for each row execute function private.notify_game_invitation_change();

create or replace function public.search_discoverable_profiles(
  search_text text,
  result_limit integer,
  for_session_id bigint,
  for_group_id bigint
)
returns table (
  id uuid,
  handle text,
  display_name text,
  avatar_url text,
  result_state text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    profile.id,
    profile.handle,
    profile.display_name,
    profile.avatar_url,
    case
      when for_session_id is not null and exists (
        select 1 from public.session_players participant
        where participant.session_id = for_session_id
          and participant.profile_id = profile.id
          and participant.removed_at is null
      ) then 'participating'
      when for_session_id is not null and exists (
        select 1 from public.game_invitations invitation
        where invitation.session_id = for_session_id
          and invitation.profile_id = profile.id
          and invitation.status = 'pending_invitee'
      ) then 'invited'
      when for_session_id is not null and exists (
        select 1 from public.game_invitations invitation
        where invitation.session_id = for_session_id
          and invitation.profile_id = profile.id
          and invitation.status = 'pending_host'
      ) then 'requested'
      when for_group_id is not null
        and public.is_accepted_group_member(for_group_id, profile.id)
        then 'group_member'
      when for_group_id is not null and exists (
        select 1 from public.group_invitations invitation
        where invitation.group_id = for_group_id
          and invitation.profile_id = profile.id
          and invitation.status = 'pending'
          and invitation.expires_at > now()
      ) then 'group_invited'
      when for_group_id is not null then 'not_in_group'
      else 'not_in_game'
    end
  from public.profiles profile
  where auth.uid() is not null
    and profile.id <> auth.uid()
    and (
      for_session_id is null
      or public.can_edit_session(for_session_id)
    )
    and (
      for_group_id is null
      or private.can_manage_group(for_group_id, auth.uid())
    )
    and profile.discoverable = true
    and profile.deleted_at is null
    and profile.suspended_at is null
    and (
      lower(coalesce(profile.handle, '')) like
        '%' || lower(btrim(search_text)) || '%'
      or lower(coalesce(profile.display_name, '')) like
        '%' || lower(btrim(search_text)) || '%'
    )
  order by
    case
      when lower(coalesce(profile.handle, '')) =
        lower(btrim(search_text)) then 0
      else 1
    end,
    lower(coalesce(profile.display_name, profile.handle, ''))
  limit least(greatest(result_limit, 1), 50);
$$;

create or replace function public.search_discoverable_profiles(
  search_text text,
  result_limit integer default 20,
  for_session_id bigint default null
)
returns table (
  id uuid,
  handle text,
  display_name text,
  avatar_url text,
  result_state text
)
language sql
stable
security definer
set search_path = ''
as $$
  select * from public.search_discoverable_profiles(
    search_text, result_limit, for_session_id, null
  );
$$;

revoke all on function public.search_discoverable_profiles(
  text, integer, bigint, bigint
) from public, anon;
grant execute on function public.search_discoverable_profiles(
  text, integer, bigint, bigint
) to authenticated;

create or replace function public.set_v2_backup_host(
  p_session_id bigint,
  p_profile_id uuid,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  game public.sessions;
  prior jsonb;
  result jsonb;
begin
  perform private.require_compatible_client();
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'set_v2_backup_host',
    jsonb_build_object(
      'session_id', p_session_id,
      'profile_id', p_profile_id
    )
  );
  if prior is not null then return prior; end if;
  game := private.require_v2_host(p_session_id);
  if game.phase not in ('draft', 'live', 'settling') then
    raise exception 'Backup host cannot be changed in this phase'
      using errcode = '22023';
  end if;
  if p_profile_id = actor
     or not exists (
       select 1 from public.profiles profile
       where profile.id = p_profile_id
         and profile.deleted_at is null
         and profile.suspended_at is null
     )
     or not (
       exists (
         select 1 from public.session_players participant
         where participant.session_id = p_session_id
           and participant.profile_id = p_profile_id
           and participant.accepted_at is not null
           and participant.removed_at is null
       )
       or (
         game.group_id is not null
         and private.can_manage_group(game.group_id, p_profile_id)
       )
     ) then
    raise exception
      'Choose another accepted participant or authorized group manager'
      using errcode = '22023';
  end if;
  update public.sessions
  set backup_host_id = p_profile_id,
      updated_at = now()
  where id = p_session_id;
  result := jsonb_build_object(
    'session_id', p_session_id,
    'backup_host_id', p_profile_id
  );
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  return result;
end;
$$;

revoke all on function public.set_v2_backup_host(bigint, uuid, uuid)
  from public, anon;
grant execute on function public.set_v2_backup_host(bigint, uuid, uuid)
  to authenticated;

create or replace function public.set_group_member_game_manager(
  p_group_id bigint,
  p_profile_id uuid,
  p_enabled boolean,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := private.require_actor();
  prior jsonb;
  result jsonb;
begin
  perform private.require_compatible_client();
  prior := private.begin_idempotent(
    actor, p_idempotency_key, 'set_group_member_game_manager',
    jsonb_build_object(
      'group_id', p_group_id,
      'profile_id', p_profile_id,
      'enabled', p_enabled
    )
  );
  if prior is not null then return prior; end if;
  if not exists (
    select 1 from public.groups
    where id = p_group_id
      and owner_id = actor
      and archived_at is null
  ) then
    raise exception 'Only the active group owner can change administrators'
      using errcode = '42501';
  end if;
  update public.group_members
  set role = case when p_enabled then 'administrator' else 'member' end,
      can_manage_games = p_enabled
  where group_id = p_group_id
    and user_id = p_profile_id
    and status = 'accepted'
    and left_at is null;
  if not found then
    raise exception 'Choose a current accepted member'
      using errcode = '22023';
  end if;
  result := jsonb_build_object(
    'group_id', p_group_id,
    'profile_id', p_profile_id,
    'can_manage_games', p_enabled
  );
  perform private.complete_idempotent(actor, p_idempotency_key, result);
  return result;
end;
$$;

revoke all on function public.set_group_member_game_manager(
  bigint, uuid, boolean, uuid
) from public, anon;
grant execute on function public.set_group_member_game_manager(
  bigint, uuid, boolean, uuid
) to authenticated;

create or replace function public.can_edit_v2_session(p_session_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.sessions game
    join public.profiles host on host.id = game.current_host_id
    where game.id = p_session_id
      and game.ledger_version = 2
      and game.current_host_id = auth.uid()
      and host.deleted_at is null
      and host.suspended_at is null
      and game.phase not in (
        'owner_unavailable_read_only',
        'orphaned_read_only',
        'cancelled'
      )
      and not exists (
        select 1
        from public.groups grouped
        where grouped.id = game.group_id
          and grouped.archived_at is not null
      )
  );
$$;

revoke all on function public.can_edit_v2_session(bigint) from public, anon;
grant execute on function public.can_edit_v2_session(bigint) to authenticated;

create or replace function public.my_games()
returns setof public.sessions
language sql
stable
security definer
set search_path = ''
as $$
  select game.*
  from public.sessions game
  where public.can_view_session(game.id)
    and (
      game.user_id = auth.uid()
      or game.current_host_id = auth.uid()
      or exists (
        select 1
        from public.session_players participant
        left join public.players legacy_player
          on legacy_player.id = participant.player_id
        where participant.session_id = game.id
          and participant.removed_at is null
          and (
            participant.profile_id = auth.uid()
            or (
              game.ledger_version = 1
              and legacy_player.linked_user_id = auth.uid()
            )
          )
      )
    )
  order by game.started_at desc;
$$;

create or replace function public.visible_games()
returns setof public.sessions
language sql
stable
security definer
set search_path = ''
as $$
  select game.*
  from public.sessions game
  where public.can_view_session(game.id)
  order by game.started_at desc;
$$;

create or replace function public.group_games(p_group_id bigint)
returns setof public.sessions
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform private.require_actor();
  if not public.is_accepted_group_member(p_group_id) then
    raise exception 'Group membership is required' using errcode = '42501';
  end if;
  return query
  select game.*
  from public.sessions game
  where public.can_view_session(game.id)
    and (
      game.group_id = p_group_id
      or (
        game.ledger_version = 1
        and exists (
          select 1
          from public.session_groups legacy_group
          where legacy_group.session_id = game.id
            and legacy_group.group_id = p_group_id
        )
      )
    )
  order by game.started_at desc;
end;
$$;

create or replace function public.game_participant_totals(
  p_session_ids bigint[]
)
returns table (
  sp_id bigint,
  session_id bigint,
  player_id bigint,
  profile_id uuid,
  display_name_snapshot text,
  buy_in_cents_total bigint,
  cash_out_cents bigint,
  net_cents bigint,
  paid_upfront boolean,
  settlement_done boolean,
  player_name text,
  player_email text,
  player_active boolean,
  linked_user_id uuid,
  was_linked_to_deleted_user boolean,
  ledger_version integer,
  finalized boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with visible_participants as (
    select
      participant.*,
      game.ledger_version,
      game.finalized
    from public.session_players participant
    join public.sessions game on game.id = participant.session_id
    where participant.session_id = any(p_session_ids)
      and public.can_view_session(participant.session_id)
  ),
  v2_money as (
    select
      event.participant_id,
      coalesce(sum(
        case
          when event.event_type in ('initial_buy_in', 'rebuy')
            then event.amount_cents
          when event.event_type = 'correction'
               and event.amount_cents > 0
            then event.amount_cents
          when event.event_type = 'reversal'
               and original.amount_cents > 0
            then event.amount_cents
          else 0
        end
      ), 0)::bigint as buy_ins,
      coalesce(sum(
        case
          when event.event_type = 'cash_out'
            then -event.amount_cents
          when event.event_type = 'correction'
               and event.amount_cents < 0
            then -event.amount_cents
          when event.event_type = 'reversal'
               and original.amount_cents < 0
            then -event.amount_cents
          else 0
        end
      ), 0)::bigint as cash_outs
    from public.ledger_events event
    left join public.ledger_events original
      on original.id = event.reverses_event_id
    where event.session_id = any(p_session_ids)
    group by event.participant_id
  )
  select
    participant.id,
    participant.session_id,
    coalesce(participant.player_id, -participant.id),
    participant.profile_id,
    participant.display_name_snapshot,
    case
      when participant.ledger_version = 2 then coalesce(money.buy_ins, 0)
      else coalesce(participant.buy_in_cents_total, 0)
    end::bigint,
    case
      when participant.ledger_version = 2
        then coalesce(money.cash_outs, 0)
      else coalesce(participant.cash_out_cents, 0)
    end::bigint,
    case
      when participant.ledger_version = 2
        then coalesce(money.cash_outs, 0) - coalesce(money.buy_ins, 0)
      else coalesce(participant.cash_out_cents, 0)
           - coalesce(participant.buy_in_cents_total, 0)
    end::bigint,
    participant.paid_upfront,
    participant.settlement_done,
    case
      when participant.ledger_version = 2
        then coalesce(participant.display_name_snapshot, 'Deleted player')
      else player.name
    end,
    null::text,
    case
      when participant.ledger_version = 2 then true
      else coalesce(player.active, false)
    end,
    case
      when participant.ledger_version = 2 then participant.profile_id
      else player.linked_user_id
    end,
    case
      when participant.ledger_version = 2 then false
      else coalesce(player.was_linked_to_deleted_user, false)
    end,
    participant.ledger_version,
    participant.finalized
  from visible_participants participant
  left join public.players player on player.id = participant.player_id
  left join v2_money money on money.participant_id = participant.id;
$$;

create or replace function public.my_stats()
returns table (
  session_id bigint,
  participant_id bigint,
  display_name_snapshot text,
  buy_in_cents bigint,
  cash_out_cents bigint,
  net_cents bigint,
  ledger_version integer
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    total.session_id,
    total.sp_id,
    total.display_name_snapshot,
    total.buy_in_cents_total,
    total.cash_out_cents,
    total.net_cents,
    total.ledger_version
  from public.game_participant_totals(
    array(
      select game.id
      from public.sessions game
      where game.finalized
        and public.can_view_session(game.id)
    )
  ) total
  where total.finalized
    and total.linked_user_id = auth.uid();
$$;

create or replace function public.group_stats(p_group_id bigint)
returns table (
  session_id bigint,
  participant_id bigint,
  profile_id uuid,
  display_name_snapshot text,
  buy_in_cents bigint,
  cash_out_cents bigint,
  net_cents bigint,
  ledger_version integer
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_accepted_group_member(p_group_id) then
    raise exception 'Group membership is required' using errcode = '42501';
  end if;
  return query
  select
    total.session_id,
    total.sp_id,
    total.linked_user_id,
    total.player_name,
    total.buy_in_cents_total,
    total.cash_out_cents,
    total.net_cents,
    total.ledger_version
  from public.game_participant_totals(
    array(select game.id from public.group_games(p_group_id) game)
  ) total
  where total.finalized;
end;
$$;

revoke all on function public.my_games() from public, anon;
revoke all on function public.visible_games() from public, anon;
revoke all on function public.group_games(bigint) from public, anon;
revoke all on function public.game_participant_totals(bigint[])
  from public, anon;
revoke all on function public.my_stats() from public, anon;
revoke all on function public.group_stats(bigint) from public, anon;
grant execute on function public.my_games() to authenticated;
grant execute on function public.visible_games() to authenticated;
grant execute on function public.group_games(bigint) to authenticated;
grant execute on function public.game_participant_totals(bigint[])
  to authenticated;
grant execute on function public.my_stats() to authenticated;
grant execute on function public.group_stats(bigint) to authenticated;

update public.app_settings
set value = 'true'
where key = 'v2_enrollment_enabled';

insert into public.feature_enrollments (feature_key, user_id)
select 'v2_game_flow', profile.id
from public.profiles profile
where profile.deleted_at is null
  and profile.suspended_at is null
on conflict do nothing;

create or replace function private.enroll_new_profile_in_v2()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce((
    select value::boolean
    from public.app_settings
    where key = 'v2_enrollment_enabled'
  ), false) then
    insert into public.feature_enrollments (feature_key, user_id)
    values ('v2_game_flow', new.id)
    on conflict do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_enroll_new_v2 on public.profiles;
create trigger profiles_enroll_new_v2
  after insert on public.profiles
  for each row execute function private.enroll_new_profile_in_v2();
